var list = [
    'img/sprites.png',
    'img/demons.png',
    'img/explosion.png',
    'img/fireballsprite.png',
    'img/mainhero.png',
    'img/monsters2.png',
    'img/wall.png',
    'img/gates.png',
    'img/mainhero2.png',
    'img/grass2.png',
    'img/spell.png',
    'img/skeleton.png',
    'img/stones.png',
    'img/sblood.png',
    'img/tree.png',
    'img/effects.png',
    'img/heart.png',
    'img/iceball.png',
    'img/terrain.png',
    'img/terrain2.png',
    'img/terrain3.png',
    'img/terrains.png',
    'img/bsprite.png',
    'img/cursor.png',
    'img/sprites2.png',
    'img/grass3.png'
];

export default list;